version: "3.9"

services:
  web:
    image: node:14.15.4-alpine3.10    # container should be created from this image
    container_name: node-project      # container name
    # build: .
    working_dir: /app   # path to the folder that project is going to be available 
    ports:
      - "3000:3000"   # ports need to be available outside the container 
    volumes:
      - .:/app    # add the root of the project to the root of the working directory
      - $HOME/rx-front/node_modules:/app/node_modules    # the node_modules folder in different location
    command: yarn start   # the command that should be run after container is built 
